apiVersion: v1
kind: Service
metadata:
  name: sbsendingemailasync-service
spec:
  type: NodePort
  selector:
    app: sbsendingemailasync
  ports:
  - port: 80
    targetPort: 10001
    nodePort: 30051
    protocol: TCP